# Generated by Django 5.2.11 on 2026-02-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='URL of the specific feed or page source')),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('TELEGRAM', 'Telegram')], default='RSS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_url', models.URLField(blank=True, help_text='Optional icon URL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_content', models.TextField()),
                ('translated_content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='aggregator.source')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
