# Generated by Django 5.2.11 on 2026-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraping_interval', models.IntegerField(default=60, help_text='Interval in minutes between scrape runs')),
            ],
            options={
                'verbose_name_plural': 'Scraper Settings',
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('RSS', 'RSS Feed'), ('FACEBOOK', 'Facebook Page'), ('TWITTER', 'Twitter/X'), ('TELEGRAM', 'Telegram Channel')], default='RSS', max_length=20),
        ),
    ]
