# Generated by Django 5.2.11 on 2026-03-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_scrapersettings_alter_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersettings',
            name='delete_old_posts_after_days',
            field=models.IntegerField(default=7, help_text='Number of days to keep posts. 0 to disable auto-delete.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('RSS', 'RSS'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'X'), ('TELEGRAM', 'Telegram')], default='RSS', max_length=20),
        ),
    ]
