# Generated by Django 5.2.11 on 2026-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_scrapersettings_delete_old_posts_after_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersettings',
            name='facebook_cookie_string',
            field=models.TextField(blank=True, help_text='Paste your full Facebook session cookie string here (e.g. sb=...; c_user=...; xs=...;). This overrides the environment variable.', null=True),
        ),
    ]
