"""
Django settings for burma_news project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)58ven!k%u$s*%+s@iofm%6vq1ino+)4bi_dvvq46!6(%@tbw5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = ['burma-news.org', 'www.burma-news.org', '127.0.0.1', 'localhost', '*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aggregator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'burma_news.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'burma_news.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    # Use PostgreSQL (or other DB) if DATABASE_URL is provided in production
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('VERCEL') or os.environ.get('VERCEL_REGION'):
    # Vercel-specific: Use /tmp for SQLite (ephemeral but writable)
    # This fixes "Database is locked" or "Read-only file system" errors
    import shutil
    
    ORIGINAL_DB = BASE_DIR / 'db.sqlite3'
    TEMP_DB = Path('/tmp/db.sqlite3')
    
    # Copy main DB to temp if it doesn't exist there yet
    # Note: This means data is lost on every cold boot, but needed for admin/login to work on Vercel w/o Postgres
    if ORIGINAL_DB.exists() and not TEMP_DB.exists():
        try:
            shutil.copy2(ORIGINAL_DB, TEMP_DB)
        except Exception as e:
            print(f"Error copying DB: {e}")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': TEMP_DB,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "aggregator" / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Scraper Settings
FACEBOOK_COOKIE_STRING = os.environ.get('FACEBOOK_COOKIE_STRING', "sb=fJWlaQOAU4JaaHRtVGzPc2Vr; datr=fJWladQM7IAIROs1QQYEKq5N; c_user=623430184; xs=24%3ATzkrXLxc78lXmA%3A2%3A1772460055%3A-1%3A-1%3A-1%3AAacy78z; presence=C%7B%22t%22%3A%22o%22%2C%22i%22%3A%22sc.141; wd=1424x444; fr=1rcJffqTPwN4LLtjv.AWee-5qCgiqUkZJqKdcosPYFGlZnRajbZiBYDD2NAlvd; locale=en_GB")
SELENIUM_HEADLESS = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
